### ISSUE TITLE
Downloading non-openable files

### ISSUE THREAD

**Issue by BanementI** [AndydeCleyre/bookme#2]
When downloading any books, they will always be in an unopenable state. It seems Springer added a captcha to the downloads, could this be it?
[10.1007%2F978-1-4020-6808-9.pdf](https://github.com/AndydeCleyre/bookme/files/4636298/10.1007.2F978-1-4020-6808-9.pdf)

**Comment by AndydeCleyre** [comment]
Darn. Yes, that's an html file with a captcha check. `bookme` is officially out of order. I don't know if I will try to work with this, but PRs are welcome.

I don't want to be in an adversarial relationship with the book provider, and I don't want to get into a cat and mouse game. I made this tool because they made access so easy, but it seems they're now trying to make it more difficult.

**Comment by AndydeCleyre** [comment]
Well, a fix was much easier than I expected, at least for now. Please confirm the new code works for you as well. Thanks for reporting!
